🐛fix: Ajuste na eficiência do passo do quality gate no teste - R:16

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -40,19 +40,9 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          for i in {1..10}; do
-            STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Equipe-CodeLand_API-2024.2-Front-End" | jq -r '.projectStatus.status')
-            echo "Attempt $i: Quality Gate Status: $STATUS"
-            if [ "$STATUS" == "OK" ]; then
-              echo "Quality Gate passed!"
-              exit 0
-            elif [ "$STATUS" == "ERROR" ]; then
-              echo "Quality Gate failed!"
-              exit 1
-            fi
-            echo "Waiting for Quality Gate to be processed..."
-            sleep 10
-          done
-          echo "Quality Gate result was not available after waiting."
-          exit 1
-
+          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Equipe-CodeLand_API-2024.2-Front-End" | jq -r '.projectStatus.status')
+          echo "Quality Gate Status: $STATUS"
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed!"
+            exit 1
+          fi
