🐛fix: Ajuste ni quality gate do sonar - R:16

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -40,9 +40,19 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Equipe-CodeLand_API-2024.2-Front-End" | jq -r '.projectStatus.status')
-          echo "Quality Gate Status: $STATUS"
-          if [ "$STATUS" != "OK" ]; then
-            echo "Quality Gate failed!"
-            exit 1
-          fi
+          for i in {1..10}; do
+            STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Equipe-CodeLand_API-2024.2-Front-End" | jq -r '.projectStatus.status')
+            echo "Attempt $i: Quality Gate Status: $STATUS"
+            if [ "$STATUS" == "OK" ]; then
+              echo "Quality Gate passed!"
+              exit 0
+            elif [ "$STATUS" == "ERROR" ]; then
+              echo "Quality Gate failed!"
+              exit 1
+            fi
+            echo "Waiting for Quality Gate to be processed..."
+            sleep 10
+          done
+          echo "Quality Gate result was not available after waiting."
+          exit 1
+
